# Generated by Django 6.0 on 2026-01-12 01:05

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcceptableUsePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("last_updated", models.CharField(max_length=255)),
                ("website_url", models.URLField(max_length=500)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "permitted_usage_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "prohibited_activities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "industry_specific_restrictions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "user_monitoring_practices",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "reporting_illegal_activities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_linked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aup_documents",
                        to="authentication.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AUPSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_number",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                (
                    "content",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="policy_generator.acceptableusepolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["section_number"],
            },
        ),
        migrations.CreateModel(
            name="CookiePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("last_updated", models.DateField()),
                (
                    "introduction",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "cookie_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "cookie_duration",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("website", models.URLField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_linked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cookie_policies",
                        to="authentication.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CookieBrowserInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("browser_name", models.CharField(max_length=100)),
                (
                    "instructions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                ("help_link", models.URLField(max_length=500)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="browser_instructions",
                        to="policy_generator.cookiepolicy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CookiePolicySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_number",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                (
                    "content",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="policy_generator.cookiepolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["section_number"],
            },
        ),
        migrations.CreateModel(
            name="CookieThirdPartyService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=255)),
                (
                    "purpose",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "opt_out_link",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="third_party_services",
                        to="policy_generator.cookiepolicy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataProcessingAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("last_updated", models.CharField(max_length=255)),
                ("website_url", models.URLField(max_length=500)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "role_controller_or_processor",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "breach_notification_timeframe",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "data_deletion_timelines",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "audit_rights",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "data_processing_locations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_linked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dpa_documents",
                        to="authentication.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DPAAnnexA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_matter_of_processing",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "duration_of_processing",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "nature_and_purpose_of_processing",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "categories_of_data_subjects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "types_of_personal_information",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "data_processing_locations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "dpa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annex_a",
                        to="policy_generator.dataprocessingagreement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DPAAnnexB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technical_measures",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "organisational_measures",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "physical_security_measures",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "security_certifications",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "dpa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annex_b",
                        to="policy_generator.dataprocessingagreement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DPADefinitions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "terms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "dpa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="definitions",
                        to="policy_generator.dataprocessingagreement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DPASection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_number",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                (
                    "content",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "dpa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="policy_generator.dataprocessingagreement",
                    ),
                ),
            ],
            options={
                "ordering": ["section_number"],
            },
        ),
        migrations.CreateModel(
            name="DPASubProcessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255)),
                (
                    "provider_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "annex_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_processors",
                        to="policy_generator.dpaannexa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("last_updated", models.DateField()),
                (
                    "introduction",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "complaints_process",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "oaic_contact",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "apps_addressed",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(
                            validators=[
                                django.core.validators.MinValueValidator(1),
                                django.core.validators.MaxValueValidator(13),
                            ]
                        ),
                        blank=True,
                        default=list,
                        help_text="List of APP numbers addressed (1–13)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_linked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_policies",
                        to="authentication.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrivacyPolicyContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("website", models.URLField(max_length=500)),
                ("postal_address", models.TextField(blank=True, null=True)),
                (
                    "policy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_info",
                        to="policy_generator.privacypolicy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrivacyPolicySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_number",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                (
                    "content",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="policy_generator.privacypolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["section_number"],
            },
        ),
        migrations.CreateModel(
            name="PrivacyPolicySubsection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subsection_number", models.CharField(max_length=20)),
                ("heading", models.CharField(max_length=255)),
                (
                    "content",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="policy_generator.privacypolicysection",
                    ),
                ),
            ],
            options={
                "ordering": ["subsection_number"],
            },
        ),
        migrations.CreateModel(
            name="TermsOfService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("last_updated", models.CharField(max_length=255)),
                ("website_url", models.URLField(max_length=500)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "service_description",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "service_type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "pricing_model",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "free_trial_terms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "payment_terms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "refund_policy",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "cancellation_terms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "eligibility_requirements",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "prohibited_activities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "user_content_license",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "user_content_responsibilities",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "intellectual_property_ownership",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "confidentiality_obligations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "consumer_guarantees",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "acl_statement",
                    models.TextField(
                        default="Nothing in these Terms excludes, restricts or modifies rights under the Australian Consumer Law."
                    ),
                ),
                (
                    "liability_limitations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "disclaimers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "termination_rights",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "dispute_resolution_process",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                ("governing_law", models.CharField(max_length=255)),
                (
                    "support_terms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "availability_terms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                (
                    "international_terms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(), blank=True, default=list
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_linked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tos_documents",
                        to="authentication.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToSSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_number",
                    models.IntegerField(
                        help_text="1-based section numbering",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                (
                    "content",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        help_text="Array of paragraphs; each item is a paragraph",
                    ),
                ),
                (
                    "terms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="policy_generator.termsofservice",
                    ),
                ),
            ],
            options={
                "ordering": ["section_number"],
            },
        ),
        migrations.AddIndex(
            model_name="acceptableusepolicy",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["permitted_usage_types"], name="policy_gene_permitt_dfa8a4_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="acceptableusepolicy",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["prohibited_activities"], name="policy_gene_prohibi_05b3ab_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="aupsection",
            constraint=models.UniqueConstraint(
                fields=("policy", "section_number"),
                name="unique_section_number_per_aup",
            ),
        ),
        migrations.AddIndex(
            model_name="cookiepolicy",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["cookie_types"], name="policy_gene_cookie__70a4ae_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="cookiepolicysection",
            constraint=models.UniqueConstraint(
                fields=("policy", "section_number"),
                name="unique_cookie_section_number_per_policy",
            ),
        ),
        migrations.AddIndex(
            model_name="dataprocessingagreement",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["data_processing_locations"],
                name="policy_gene_data_pr_e6091d_gin",
            ),
        ),
        migrations.AddIndex(
            model_name="dataprocessingagreement",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["role_controller_or_processor"],
                name="policy_gene_role_co_0579a3_gin",
            ),
        ),
        migrations.AddConstraint(
            model_name="dpasection",
            constraint=models.UniqueConstraint(
                fields=("dpa", "section_number"), name="unique_section_number_per_dpa"
            ),
        ),
        migrations.AddIndex(
            model_name="privacypolicy",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["apps_addressed"], name="policy_gene_apps_ad_210840_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="privacypolicysection",
            constraint=models.UniqueConstraint(
                fields=("policy", "section_number"),
                name="unique_privacy_section_number_per_policy",
            ),
        ),
        migrations.AddConstraint(
            model_name="privacypolicysubsection",
            constraint=models.UniqueConstraint(
                fields=("section", "subsection_number"),
                name="unique_privacy_subsection_number_per_section",
            ),
        ),
        migrations.AddIndex(
            model_name="termsofservice",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["service_description"], name="policy_gene_service_60ba89_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="termsofservice",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["service_type"], name="policy_gene_service_ce969e_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="termsofservice",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["prohibited_activities"], name="policy_gene_prohibi_39d900_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="termsofservice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "acl_statement",
                        "Nothing in these Terms excludes, restricts or modifies rights under the Australian Consumer Law.",
                    )
                ),
                name="tos_acl_statement_exact",
            ),
        ),
        migrations.AddConstraint(
            model_name="tossection",
            constraint=models.UniqueConstraint(
                fields=("terms", "section_number"),
                name="unique_section_number_per_terms",
            ),
        ),
    ]
