# Generated by Django 6.0 on 2026-01-12 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("policy_generator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="termsofservice",
            name="tos_acl_statement_exact",
        ),
    ]
